# Generated by Django 3.2.8 on 2021-11-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_creation_description_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('img', models.ImageField(upload_to='works', verbose_name='画像')),
                ('url', models.URLField(verbose_name='URL')),
                ('date', models.DateField(blank=True, null=True, verbose_name='公開日')),
            ],
            options={
                'verbose_name_plural': '作品集',
            },
        ),
        migrations.DeleteModel(
            name='Creation',
        ),
    ]
